### ISSUE TITLE
Implement `align_corners` and `recompute_scale_factor`

### ISSUE THREAD

**Issue by fmassa** [vfdev-5/interpolate-tensoriterator#4]
Those two options are needed before we can merge our implementation in PyTorch.

I expect that we will only need to modify `ti_compute_indices_weights_linear` to provide slightly different Tensor values

**Comment by vfdev-5** [comment]
Tried to fix this issue here : https://github.com/vfdev-5/interpolate-tensoriterator/commit/0e515654976e9213e7a3c3e0ef4dc9a5c803cca9
Let me know what do you think.
